import type { Club } from "./types";

export const mockClubs: Club[] = [
  {
    id: "club-1",
    title: "Sunrise Study Circle",
    description: "Quiet accountability sessions with lo-fi playlists and shared to-do lists.",
    category: "study",
    city: "New Haven",
    location: "Sterling Library",
    isRemote: false,
    joinPolicy: "open",
    distanceKm: 1.4,
    memberCount: 18,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    creator: {
      id: "user-1",
      name: "Avery",
      handle: "@avery",
    },
  },
  {
    id: "club-2",
    title: "Campus Night Runs",
    description: "Three miles, good lighting, and a coffee stop after.",
    category: "sports",
    city: "Berkeley",
    location: "Memorial Glade",
    isRemote: false,
    joinPolicy: "application",
    distanceKm: 3.2,
    memberCount: 27,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    creator: {
      id: "user-2",
      name: "Jordan",
      handle: "@jordan",
    },
  },
  {
    id: "club-3",
    title: "Startup Sketch Lab",
    description: "Weekly sprints to turn napkin ideas into clickable prototypes.",
    category: "build",
    city: "Austin",
    location: "Innovation Hub",
    isRemote: false,
    joinPolicy: "open",
    distanceKm: 5.8,
    memberCount: 12,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    creator: {
      id: "user-3",
      name: "Priya",
      handle: "@priya",
    },
  },
  {
    id: "club-4",
    title: "Remote Book Sprints",
    description: "Two chapters per week with async notes and Friday recaps.",
    category: "creative",
    city: null,
    location: "Remote",
    isRemote: true,
    joinPolicy: "application",
    distanceKm: null,
    memberCount: 42,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
    creator: {
      id: "user-4",
      name: "Sam",
      handle: "@sam",
    },
  },
  {
    id: "club-5",
    title: "Sunset Yoga Circle",
    description: "Stretch, breathe, and close the day with a 30-minute flow.",
    category: "wellness",
    city: "Santa Cruz",
    location: "East Field",
    isRemote: false,
    joinPolicy: "open",
    distanceKm: 2.1,
    memberCount: 9,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    creator: {
      id: "user-5",
      name: "Kai",
      handle: "@kai",
    },
  },
];
