import type { RequestCard } from "@lockedin/shared";

export const requests: RequestCard[] = [
  {
    id: "request-1",
    title: "Anyone down to shoot hoops?",
    description: "Casual run, all skill levels. Bring music.",
    location: "Rec Center Courts",
    city: "Ann Arbor",
    isRemote: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    tags: ["sports", "fun"],
    urgency: "low",
    creator: {
      id: "user-1",
      name: "Avery Cho",
      handle: "@averycodes",
    },
    likeCount: 7,
  },
  {
    id: "request-2",
    title: "Need help carrying a desk",
    description: "One flight of stairs, pizza on me.",
    location: "North Quad",
    city: "Ann Arbor",
    isRemote: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    tags: ["help", "moving"],
    urgency: "high",
    creator: {
      id: "user-2",
      name: "Samira Patel",
      handle: "@samirawins",
    },
    likeCount: 18,
  },
  {
    id: "request-3",
    title: "Looking for a hackathon teammate",
    description: "You bring design or ML. I bring snacks + backend.",
    location: "Engineering Hall",
    city: "Ann Arbor",
    isRemote: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    tags: ["build", "cofounder"],
    urgency: "medium",
    creator: {
      id: "user-3",
      name: "Miles Grant",
      handle: "@milesmoves",
    },
    likeCount: 12,
  },
  {
    id: "request-4",
    title: "Need a photographer for club pics",
    description: "30 minutes, golden hour lighting.",
    location: "Student Union Steps",
    city: "Ann Arbor",
    isRemote: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 160).toISOString(),
    tags: ["creative", "help"],
    urgency: "low",
    creator: {
      id: "user-4",
      name: "Jess Rivera",
      handle: "@jesssnaps",
    },
    likeCount: 3,
  },
  {
    id: "request-5",
    title: "Remote Figma review",
    description: "Need feedback on a landing page, quick Loom ok.",
    location: "Remote",
    city: null,
    isRemote: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    tags: ["design", "help"],
    urgency: "medium",
    creator: {
      id: "user-2",
      name: "Samira Patel",
      handle: "@samirawins",
    },
    likeCount: 6,
  },
];
